import { Analytics } from '@vercel/analytics/react';
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Geist, Geist_Mono } from 'next/font/google';
import type { Metadata } from 'next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastProvider } from '@/components/ToastProvider';
import ConvexClientProvider from '@/components/ConvexClientProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider
        appearance={{
          baseTheme: [dark],
          variables: {
            colorPrimary: "#00AE98",
            colorTextSecondary: "#707070",
            colorShimmer: "#00AE98",
          },
          layout: {
            animations: true,
            shimmer: true,
          },
        }}
      >
        <ConvexClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <ToastProvider />
            <body className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, 'bg-gray-100 text-white min-h-screen')}>
              <main className="min-h-screen bg-gray-100 pt-16">
                {children}
              </main>
            </body>
            <Analytics />
            <SpeedInsights />
          </ThemeProvider>
        </ConvexClientProvider>
      </ClerkProvider>
    </html>
  );
};